apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-dep
  namespace: argocd-spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: 69966/springgradleimage:1.1.1
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: spring-vol
            mountPath: /app/src/main/resources/images
      volumes:
        - name: spring-vol
          nfs:
            server: 10.148.0.19
            path: /opt/nfs/data

---
# Path: spring-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
  namespace: argocd-spring
spec:
  type: ClusterIP
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
# Path: spring-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ingress
  namespace: argocd-spring
  annotations:
    kubernetes.io/ingressClassName: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - b.sen-pai.live
    secretName: spring-tls
  rules:
  - host: b.sen-pai.live
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-svc
            port:
              number: 8080